version: '2'
services:
  app:
    build: app/
    volumes:
      - ./app/src/:/usr/src/app/
  web:
    image: nginx
    links:
      - app
    ports:
      - 8880:80
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl
      - ./frontend/public:/frontend
